### ISSUE TITLE
Behöver tips angående "PATCH" & "DELETE"

### ISSUE THREAD

**Issue by Zerowhizkey** [cme-osuka/webbserverdatabaser#11]
Jag har testat på lite olika sätt men får inte riktigt till det och tänker att jag kanske håller på med fel "fs" grej.
Min fråga är då har någon tips på vad jag kan söka mig vidare på att använda till dessa två ?

Jag har/håller på med fs.writeFileSync & fs.unlink

**Comment by antonjaldegren** [comment]
Löst i breakout room 5 på teams! :)

**Comment by Zerowhizkey** [comment]
Thank you master Anton!
