### ISSUE TITLE
Hittar inte Exempel på client & server! Hjälp!

### ISSUE THREAD

**Issue by Zerowhizkey** [cme-osuka/webbserverdatabaser#12]
Hittar inte måndagens exemplar på client side och server side

**Comment by Flying0101** [comment]
du hittar det här https://github.com/cme-osuka/webbserverdatabaser/blob/main/week2/lecture6/solutions/kontaktlista/server.js

**Comment by Zerowhizkey** [comment]
så jävla bra! tack!
