### ISSUE TITLE
Svårt att komma igång med K1?

### ISSUE THREAD

**Issue by sawariz0r** [cme-osuka/webbserverdatabaser#13]
Det kan vara lite klurigt att komma igång med en uppgift som denna, så jag tänkte dela med mig av några tips som kan vara en hjälp på vägen:

1. Börja inte med Frontenden, så slipper du jobba mot två kodbaser samtidigt. Det är mycket lättare att implementera funktionaliteten på Frontenden när Backenden är så gott som klar.
2. Använd REST-klienter som Insomnia och Postman för att testa dina endpoints. Du har alla requests sparade och samlade på ett ställe istället för att behöva testa det i konsollen i webbläsaren.
3. Bygg en endpoint i taget. Kolla i Issues för att se om någon haft samma problem som du.
4. Console.logga saker som du är osäker på vad det är - får du rätt metod i `req.method`? _Console.logga!_ 

## Endpoints 
`GET /todos - "Hämta alla todos"`
Används för att hämta alla todos från Backenden
`GET /todos/:id - "Hämta en todo"`
Används för att hämta en enstaka todo, där `:id` motsvarar ett unikt id på todon. 
Id't är det bästa sättet att särskilja todos och kunna uppdatera enstaka todos - och du kan använda den som key i React till exempel!
`POST /todos - "Lägg till en todo"`
Används för att lägga till en todo. Kom ihåg att passa med headern `Content-Type` med den typen av datan du skickar!
`PUT /todos/:id - "Ändra en todo (full)`
Används för att ändra en resurs, eller en todo i vårt API. Där `:id` motsvarar ett unikt id på todon. `(full)` innebär att du behöver passa med hela objektet du vill ersätta - eftersom PUT används för att skriva över hela objektet.
`PATCH /todos/:id - "Ändra en todo (partial)"`
Används för att ändra en resurs och förväxlas lätt med PUT. Skillnaden här är att man ska bara behöva passa med det vi vill uppdatera, exempelvis om vi har `id`, `name`, `status` i vårt todo-objekt - så ska vi bara behöva passa med det värdet vi vill uppdatera istället för hela objektet. 
`DELETE /todos/:id - "Ta bort en todo"`
Används för att ta bort en resurs, till exempel när du ska ta bort en todo från din lista. Här behöver du inte skicka med någon body - eftersom du redan skickar med `:id` i urlen till `DELETE`. Det är allt du behöver för att veta vilken som ska tas bort från listan!

**Behöver man använda alla endpoints i Frontenden?** 
Nej, men de ska finnas implementerade på backenden ifall man skulle vilja använda dessa!

**Comment by Zerowhizkey** [comment]
Tips också är att kika på denna : https://github.com/cme-osuka/webbserverdatabaser/tree/main/week3/lecture7/examples/communication-example
