### ISSUE TITLE
Delete todos/id

### ISSUE THREAD

**Issue by Flying0101** [cme-osuka/webbserverdatabaser#14]
som titeln lyder har jag problem med delete, något missar jag men vad... 

kod för delete:
 testDat.filter(todo => parseInt(todo.id) !== requestedId);
har försökt med olika varianter men utan framgång, blir galen på skiten. några tips?

**Comment by sawariz0r** [comment]
Kan det vara så att requestedId inte är vad du tänker dig? 

Parsar du requestedId?

**Comment by Zerowhizkey** [comment]
Skicka lite bilder på det runt om också :D 
annars om du har tid nu eller senare kanske jag kan kika lite med dig

**Comment by Flying0101** [comment]
> Kan det vara så att requestedId inte är vad du tänker dig?
> 
> Parsar du requestedId?

-------

jo men requestedId tar numret från todos/:id(ex 2) 
som är en sträng som jag sedan kör parseInt på, jag jämför alltså två nummer /ints ?

**Comment by Flying0101** [comment]
löste problemet... hade deklarerat fel... const istället för let, funkar med let nu.......... tack för hjälpen dock!
