### ISSUE TITLE
PUT / PATCH ? 

### ISSUE THREAD

**Issue by Flying0101** [cme-osuka/webbserverdatabaser#15]
PUT /todos/:id - Ändra en Todo (full)
PATCH /todos/:id - Ändra en todo (partial)

förvirrad gällande vilken som gör vad, skulle man kunna använda PATCH för att markera en todo som färdig och PUT för att ändra innehållet i en todo?       ʕ•́ᴥ•̀ʔっ

**Comment by Zerowhizkey** [comment]
som ett t.ex så använder jag PATCH för att ändra min boolean till true eller false, medans min PUT måste hantera mycket mera

**Comment by Zerowhizkey** [comment]
Haha Tror jag kanske inte sa helt korrekt, Min PATCH som te.x skulle kunna ändra flera saker, men hade räckt med 1.

**Comment by Zerowhizkey** [comment]
Svarade men tog bort, insåg att jag kanske inte fullt ut fattade skillnaden heller :D mina gör samma sak ish men använder endast PATCH till frontend för att ändra Boolean till true eller false

**Comment by Flying0101** [comment]
aaah Aaa men nu förstår jag lite bättre, ty!
