### ISSUE TITLE
Nodemon ERR --> Powershell Terminalen [Windows?]

### ISSUE THREAD

**Issue by aleksmagnusson** [cme-osuka/webbserverdatabaser#17]
Hej!
Är det någon som använder Nodemon och får fel när de kör i konsolen (terminalen) på Windows i VScode?

Se felmeddelande nedan:
![image](https://user-images.githubusercontent.com/92426232/169851433-37f946fc-a5cc-494b-8e0d-9276fe2e3434.png)

Läste även på länken och tänkte om någon har en lösning på problemlösningen eller stött på denna (som förmodligen använder Windows)?

Länk till Execution_Policies: https://docs.microsoft.com/sv-se/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.2

👍🏽 🦺 ⛑️ 
#nodemon

**Comment by sawariz0r** [comment]
Funkar `node server.js`?

**Comment by sawariz0r** [comment]
Testa gärna om nodemon funkar i git bash, för det ser ut som det är ett Powershell-error :)

**Comment by aleksmagnusson** [comment]
Nodemon fungerar utmärkt med Git Bash! Windows och VScode har fortfarande en bugg/blockad som inte vill lösa sig om man inte ändrar hårt i powershell.

**Comment by sawariz0r** [comment]
Kan rekommendera att använda git bash för nodemon isåfall 👍

**Comment by sawariz0r** [comment]
Stänger denna
