### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by Smokinglirare** [cme-osuka/webbserverdatabaser#20]
Hej, var det någon som hade en bra lösning på CORS problematiken? Får det inte att fungera.

**Comment by antonjaldegren** [comment]
Hejsan!

Alla mina problem löstes när jag lade till denna header i responsen på requests med samtliga metoder:
```
res.setHeader("Access-Control-Allow-Origin", "*");
```
Samt la till dessa två (utöver den ovan) specifikt för hanteringen av OPTIONS-requests:
```
res.setHeader("Access-Control-Allow-Methods", "GET, PATCH, DELETE, OPTIONS, POST, PUT");
res.setHeader("Access-Control-Allow-Headers", "Content-Type");
```

**Comment by Smokinglirare** [comment]
Ja okej har provat det där, men får fortsatt det här felet. 

"Access to fetch at 'http://localhost:5000/todos' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status."

**Comment by sawariz0r** [comment]
`Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`
Indikerar att du förmodligen har CORS-headers och att de fungerar, men att den får en error-statuskod (404 kanske?) istället för en 200-kod (ok). 

En workaround är att lägga till en if-sats innan de andra routesen som kollar om det är en request gjord med OPTIONS-metoden och svarar med statuskoden 200:
```js
const server = http.createServer((req, res) => {
  
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, PATCH, DELETE, OPTIONS, POST, PUT");
    res.setHeader("Access-Control-Allow-Headers", "Content-Type");
  
    res.statusCode = 200;
    res.end();
  }

// ... Resten av applikationen
```

**Comment by Smokinglirare** [comment]
Det där löste problemet, tackar!
