### ISSUE TITLE
Server kraschar vid PATCH-anrop

### ISSUE THREAD

**Issue by Binnaz-CME** [cme-osuka/webbserverdatabaser#23]
Jag har problem med att servern kraschar när jag gör PATCH anrop. Enligt network-loggen funkar patch men när det ska göras en ny GET är det något som går fel vid parse av JSON när fs.readFile ska läsa min json-fil. 

Ibland funkar det att skriva till filen alltså ändra isDone till true men därefter skriver den inte över isDone till false. Det är i det här läget den kraschar.

Någon som har några förslag?

<img width="1440" alt="Screenshot 2022-05-26 at 10 17 32" src="https://user-images.githubusercontent.com/92431375/170449039-4cc27bf0-8228-47c3-9fbb-d3b4d6301ab7.png">

<img width="1440" alt="Screenshot 2022-05-26 at 10 17 16" src="https://user-images.githubusercontent.com/92431375/170449066-9c1aea84-66b5-42e2-886b-260d2039ee11.png">

Troligtvis blir det fel när json-filen ska läsas igen vid GET-anropet efter PATCH.

**Comment by sawariz0r** [comment]
@Binnaz-CME Om jag förstod dig rätt, så fungerar det när den är true?

**Comment by Binnaz-CME** [comment]
Det funkar att ändra värdet på isDone en gång. Därefter skickas PATCH anrop och jag kan logga att värdet ändras men ingenting skrivs till json-filen. Därefter kraschar den... det är lite sporadiskt.

**Comment by Zerowhizkey** [comment]
Kanske är helt ute och Cyklar men kan det hjälpa å ha en return för att inte få den att "crasha/stängas av" ?

**Comment by Binnaz-CME** [comment]
Nu funkar det inte att skriva till json-filen alls. Men jag ser att jag skickar in ett anrop med true och false. 

Hur då, Marcus??

**Comment by sawariz0r** [comment]
Det ser ut som du kollar data.isDone, medans när du loggar `done` får du `{ done: true }`.
Har du möjlighet att console.logga `todo` (rad 108) och `stringTodos` (rad 116)? :)

**Comment by Zerowhizkey** [comment]
Tror jag är ute och cyklar :D

**Comment by Binnaz-CME** [comment]
Resultatet av upprepade klick på 'Done' knappen alltså patchanrop med console.log på rad 108 0ch 116.

<img width="824" alt="Screenshot 2022-05-26 at 12 00 04" src="https://user-images.githubusercontent.com/92431375/170465812-def68121-7210-4cfc-ba7a-89af4536709b.png">

**Comment by Zerowhizkey** [comment]
har du tid å komma till teams?

**Comment by Binnaz-CME** [comment]
Jag har ändrat done till isDone, nu skriver den över filen men servern kraschar fortfarande.

**Comment by sawariz0r** [comment]
Hmm.. SyntaxError pekar på att det är något med läs/skriv-biten, så det kan vara något sånt. Jag kan hoppa in i teams med er ett kort ögonblick om ni vill!

**Comment by Binnaz-CME** [comment]
Gärna :-)

**Comment by Zerowhizkey** [comment]
hoppar in i BR1

**Comment by sawariz0r** [comment]
Note: Visade sig vara problem med fs.readFile, eftersom den är asynkron. Så jag misstänker att den försökte läsa filen samtidigt som den skrev till filen på raderna under :)

**Comment by sawariz0r** [comment]
Skickar poängen till @Zerowhizkey för att han hjälpte till!
