### ISSUE TITLE
allt slutade funka idag!

### ISSUE THREAD

**Issue by Flying0101** [cme-osuka/webbserverdatabaser#25]
som titeln lyder... igår kväll blev jag klar med allt och allt funkade felfritt, idag funkar inte ett skit.... varför? 
har inte ändrat något.... dubbelkollat allt... min backend funkar fine med insomnia, inget konstigt på front-enden.... T-T

**Comment by sawariz0r** [comment]
Får du något error?

**Comment by Flying0101** [comment]
nej inget...

**Comment by Flying0101** [comment]
backenden funkar hur bra som helst med insomnia, i network tabben görs requests ja

**Comment by Flying0101** [comment]
jätte konstigt

**Comment by sawariz0r** [comment]
Kan du ta en screenshot? Får du OK-statuskoder? Hur ser responsen i requestsen ut?

**Comment by Flying0101** [comment]
https://user-images.githubusercontent.com/92680078/170490523-a7867972-4240-46db-afbc-c04481264f6b.mp4

**Comment by Flying0101** [comment]
har en form men inte e.preventDefault(), sidan refreshas varje gång jag kör en function som till exempel delete eller complete för att uppdatera listan, jag har haft koden så sen början och aldrig haft problem förstår inte varför jag får det idag och inte igår.. 

yup.. jag undrar också varför jag har ett ? i urlen... 

det ända jag kommer att tänka på som jag har gjort efter igår är att jag ändrade namn på fil mappen...
 från "front" till "K1-frontend" men det ska väl inte påverka koden?

**Comment by sawariz0r** [comment]
Det är inte rekommenderat att refresha sidan, eftersom det kan avbryta requests (generellt inte rekommenderat att refresha SPA's som React). Bättre att du fetchar den uppdaterade datan när du lagt till eller uppdaterat en todo :)

**Comment by Flying0101** [comment]
har precis provat göra det utan framgång, knapparna funkar inte alls förstår inte varför....

**Comment by sawariz0r** [comment]
> har precis provat göra det utan framgång, knapparna funkar inte alls förstår inte varför....

Kan du skicka screenshots på hur funktionerna som fetchar datan i din frontend ser ut?

**Comment by Flying0101** [comment]
![Screenshot (710)](https://user-images.githubusercontent.com/92680078/170493238-2f935062-e9db-411c-92b3-e03c7c25e02c.png)

här är delete och complete funktionerna utan fetch, vanligtvis när jag kör på delete och den går igenom får jag ett "test" på backend git bashen, men verkar som att mina funktioner inte funkar...

**Comment by sawariz0r** [comment]
Och där du använder submit/form?

**Comment by Flying0101** [comment]
<form className="app" onSubmit={clear} >

        <input type="text" placeholder="Type your task here...." value={send} onChange={(e) => setSend(e.target.value)} />

        <button type="submit" className="sheesh" onClick={() => post()}>Add</button>

      </form>

**Comment by Flying0101** [comment]
<form className="app" onSubmit={clear} >

        <input type="text" placeholder="Type your task here...." value={send} onChange={(e) => setSend(e.target.value)} />

        <button type="submit" className="sheesh" onClick={() => post()}>Add</button>

      </form>

**Comment by Flying0101** [comment]
<form className="app" onSubmit={clear} >
        <input type="text" placeholder="Type your task here...." value={send} onChange={(e) => setSend(e.target.value)} />
        <button type="submit" className="sheesh" onClick={() => post()}>Add</button>
      </form>

**Comment by sawariz0r** [comment]
Hur ser <form onSubmit={}> ut?

**Comment by Flying0101** [comment]
![Screenshot (711)](https://user-images.githubusercontent.com/92680078/170494081-a2060183-35dc-430c-b47c-049769a70343.png)

**Comment by Flying0101** [comment]
på onSubmit kallar jag på en function som renser min todo useState, har funkat hur bra som helst sen start

**Comment by sawariz0r** [comment]
Hur ser funktionen `clear` ut?

**Comment by Flying0101** [comment]
![Screenshot (712)](https://user-images.githubusercontent.com/92680078/170494324-82ce2275-d5bc-44be-bb66-0a95ebd5a837.png)

**Comment by Flying0101** [comment]
återställer inputen där jag skriver mina nya todos

**Comment by sawariz0r** [comment]
Testa lägga till e (eller event) som parameter i clear
```js
function clear(e) {
```

och se till att du kallar på `e.preventDefault()` i clear-funktionen:

```js
function clear(e) {
e.preventDefault();
setSend("");
}
```

**Comment by Flying0101** [comment]
nope ingen framgång

**Comment by sawariz0r** [comment]
På din bild här, indikerar den att den väntar på ett svar från servern på "GET /todos". 
Får du inget error i din backend här? 
<img width="342" alt="image" src="https://user-images.githubusercontent.com/17275925/170495334-1e874f78-8f2d-4de5-af92-52da19c24483.png">

**Comment by Flying0101** [comment]
nope

**Comment by Flying0101** [comment]
mina funktioner i front funkar samma med backend, men som du säger så verkar dem inte vilja snacka med varandra och få min app o funka....

**Comment by sawariz0r** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/17275925/170495564-1582aa04-95f7-4987-b4aa-5d3b7f1dc1c8.png">

I dina requests skulle du även behöva hantera svaret du får, antingen med async/await eller .then
```js
axios.delete("").then(res => {
// Hämta den uppdaterade datan
// och uppdatera ditt state
// getTasks()
})
```

**Comment by sawariz0r** [comment]
För din Frontend vet inte att något ändrats om du inte frågar din backend om den uppdaterade informationen, så du skulle behöva hämta `GET /todos` igen och uppdatera statet

**Comment by Flying0101** [comment]
precis men det gör jag med min reload(), har försökt med andra metoder där jag inte refreshar sidan men det funkar inte

**Comment by Flying0101** [comment]
window.location.reload() efter att jag kallar på önskade funktionen, har tagit bort den och försökt o ladda hem datan, ingen framgång där heller

**Comment by sawariz0r** [comment]
Försök undvika att ladda om sidan om du inte absolut måste :) 

Hur ser funktionen ut som hämtar datan från början?

**Comment by Flying0101** [comment]
![Screenshot (713)](https://user-images.githubusercontent.com/92680078/170498143-7c939002-fd08-4fd8-ab81-3edcb998de2a.png)

**Comment by Flying0101** [comment]
min kod funkade perfekt igår........... jag var klar.....

**Comment by sawariz0r** [comment]
Lägg den axios-funktionen i en funktion, och kalla på den istället. 

```js
function getData() {
  axios.get("URL")
    .then((res) => {
      setTodo(res.data)
    }
}
```

och kalla på den i din useEffect:
```js
useEffect(() => {
  getData();
}, [])
```

Och kalla på den varje gång du behöver refresha med todos, istället för att ladda om sidan

**Comment by sawariz0r** [comment]
> På din bild här, indikerar den att den väntar på ett svar från servern på "GET /todos". Får du inget error i din backend här? <img alt="image" width="342" src="https://user-images.githubusercontent.com/17275925/170495334-1e874f78-8f2d-4de5-af92-52da19c24483.png">

Men som den här, här väntar den på en request som aldrig blir färdig - det kan vara så att du inte kallar på res.end() för att signalera att responsen är redo att skickas tillbaka. Hur ser den routen ut?

**Comment by Flying0101** [comment]
ingen framgång där heller.. tog bort allt som refreshade sidan och kallade på funktionen men inget händer med backenden... 

jo men precis, jag har en res.end på alla

**Comment by sawariz0r** [comment]
Hur ser den routen ut?

**Comment by Flying0101** [comment]
![Screenshot (714)](https://user-images.githubusercontent.com/92680078/170500764-0f5623d8-8a76-4d23-be12-9952e867e895.png)

**Comment by Flying0101** [comment]
där har du koden som hämtar alla todos och den som lägger till(post)

**Comment by sawariz0r** [comment]
Kan du logga innehållet i `routes`? När den säger "väntar" i Network-tabben i webbläsaren?

**Comment by sawariz0r** [comment]
Återkommer eventuellt senare ikväll, ska iväg på middag om ett ögonblick. Men det ser ut som din request till /todos inte blir klar av någon anledning eftersom den sitter och "väntar".

**Comment by Flying0101** [comment]
ok tack för hjälpen, ska kika vidare!

**Comment by Flying0101** [comment]
![Screenshot (716)](https://user-images.githubusercontent.com/92680078/170506829-03b89e28-c4f3-414d-ab98-e007e4d068e9.png)

har kollat igenom min front och back och allt funkar som det ska, problemet verkar vara det jag skickade på bilden som jag inte förstår

**Comment by Flying0101** [comment]
jag har slut på ideer... inget ger framsteg

**Comment by aleksmagnusson** [comment]
Du kan ju återkalla till en tidigare commit från igår om allting fungerade.
Har du kommit framåt eller står det still? @Flying0101 !?

**Comment by Flying0101** [comment]
det står still har försökt med allt, tyvärr körde jag inte med commits.... har inte ändrat något sen igår kväll när jag testade allt och allt funkade...

**Comment by Flying0101** [comment]
ska fortsätta försöka lite till sen får det vara

**Comment by Flying0101** [comment]
jag kan mejla dig koden!

**Comment by aleksmagnusson** [comment]
Eller ladda upp om du har skapat ett Github-repo så kan jag hämta i git rätt snabbt.

**Comment by aleksmagnusson** [comment]
Min mail finns här: https://linktr.ee/aleks.magnusson längst ner på brev-iconen aka 'mailto:'

**Comment by aleksmagnusson** [comment]
// Ser att du håller på att ladda upp. Kollar snart! Ska iväg och lämna en sak. // @Flying0101

**Comment by aleksmagnusson** [comment]
Hej... blev av med internet i mitt område. Det har kommit tillbaka nu och tänkte kika på ditt repo/kod @Flying0101

**Comment by Flying0101** [comment]
var inget fel på min kod typ behövde bara ta hand om OPTIONS som jag inte fick igår... löste!

**Comment by aleksmagnusson** [comment]
SHEEESH! Snyggt jobbat! Hoppas samvetet finns kvar. ^^
