### ISSUE TITLE
Frågor om K2

### ISSUE THREAD

**Issue by sawariz0r** [cme-osuka/webbserverdatabaser#26]
## Vad för databas ska vi använda oss av?
För detta kommer vi att använda oss av en SQL-databas, förslagsvis `SQLite`. (Enklast!)
Då slipper vi tänka på anslutningsdetaljer och vi kan commita vår databas-fil till Git-repot.
(Det gör vi inte normalt sett, men eftersom ändamålet är att testa er inlämning så går det bra!)

## Vad för data borde boken innehålla?
Förslag:

```
id - int
title - string
author - string
genre - string
```

## Vad är ett lämpligt meddelande och statuskod?
ex. en request till GET /books/:id där id't inte finns, bör den svara med:

```js
// Statuskod 
404 
// JSON
{ status: "error", message: "The book with id {x} could not be found" } 
```

## Vad skickar jag till en PUT och PATCH? Vad är skillnaden?
PUT ersätter resursen med det du skickar in, så skulle du vilja ändra en bok behöver du skickar med samtliga värden, även de som inte ändrats. 
```
PUT /books/:id 
{ id: 1, title: "En bok", author: "Ryan Dahl", genre: "Sci-fi" }
```

## PATCH uppdaterar du en del av resursen, där du bara behöver skicka med det värdet du vill ändra - men behåller övriga värden intakta.
```
PATCH /books/:id 
{ title: "En bouk fast pau rejn Skaunska" }
```

## Vad ska en POST svara med när den är klar?
Den svarar alltid med statuskod och även ibland det objektet, den resursen du skapat:
```
// Statuskod
201
// JSON-svar
{ id: 2, title: "Hur man skapar en bok", author: "Bryan Dahl", genre: "thriller" }
```

## Får man skapa en Frontend också?
Absolut! Jag kommer dock inte betygsätta den, men det är en bra övning!

## Hur kombinerar man SQL och JSON?
Vi kommer titta på detta under nästa vecka, men ett exempel kan du hitta här:
https://github.com/cme-osuka/webbserverdatabaser/tree/main/week5/lecture14/examples/express-sqlite-example

## Får man använda UUID? 
Absolut! Enda kravet på bibliotek/paket är att du ska använda Express, annars får du lov att använda i princip vad du vill.

## VG: Kommer vi gå igenom JWT?
Det kommer vi göra nästa vecka! 

## VG: Ska man kunna låna hur många av en bok som helst eller ska det finnas ett antal?
Detta är frivilligt, om du vill testa på att implementera ett antal - ex. om du säger att en bok har `amount` och ett antal lånbara böcker, så skulle du kunna skriva logik som kollar antalet låne-transaktioner och ser hur många som finns ute på lån just nu.

**Comment by NilsFaelt** [comment]
Ska databasen bara vara en fil (db)som i testet vi gjorde  eller ska den vara uppkopplad mot en riktig databas?

**Comment by sawariz0r** [comment]
> 

Jag rekommenderar att du använder en fil och SQLite, annars måste du se till att jag får alla anslutningsdetaljer så jag kan ansluta till din databas (url, username, password osv).

**Comment by Zerowhizkey** [comment]
Jag började idag med uppgiften OCH har redan gjort på ett sätt, men frågar iaf om tips på vad ni/någon tycker är bästa approach.
Borde man mixa allt direkt med express, MVC & sql ELLER ta ett steg i taget? 
Ett steg i taget då typ att man börjar och lägga mestadels i  server.js filen och bygger ut det sakta men säkert ?
Give me your best 
approaches!

**Comment by NilsFaelt** [comment]
Jag tycker de är nice o börja me o strukturera upp alla mappar enligt mvc och lägga grunden först o sen börja ta tag i problemen.
Jag har testat två olika men tyckte de va absolut skönast om implementera sqlite samtidigt som  man bygger applikationen.
Blev grötigt o försöka få allt o funka efter man va klar med all node.js o sen lägga in sqlite o db.
My opinion
