### ISSUE TITLE
Problem med installera npm i sqlite3

### ISSUE THREAD

**Issue by linda-94-andersson** [cme-osuka/webbserverdatabaser#27]
**Beskriv problemet**
Jag skulle installera sqlite3 via npm men den ger mig bara error. Detta är första gången jag försökt installera sqlite3.

**Vad jag försöker göra**
Jag körde npm i sqlite3, till och med kopierade från https://www.npmjs.com/package/sqlite3 i fall jag skrivit fel men fick samma error.

**Vad du förväntar dig**
Installera sqlite3

**Screenshots**
Error koden:
![image](https://user-images.githubusercontent.com/87518211/172012957-96fe363e-ecb5-4de4-b3a1-8892dc40ac90.png)
Min package.json och mappstruktur: 
![image](https://user-images.githubusercontent.com/87518211/172013135-ebefab4d-15b1-46bc-8cff-0ae8447eb149.png)

**Övrigt**
Min gissning är att jag kanske saknar något npm pack installerat globalt? Har kört node utan problem förut. Någon annan som har haft likande problem innan jag raderar alla modules och installerar om allting?

**Comment by sawariz0r** [comment]
Har hittat ett par andra med samma problem och som också har det liggandes på OneDrive. Kan du testa om du får samma problem med projektet utanför en OneDrive-mapp?

**Comment by sawariz0r** [comment]
Kan också ha något att göra med mellanslag i mappnamnen, det är min andra gissning!

**Comment by sawariz0r** [comment]
https://github.com/nodejs/node-gyp/issues/439

**Comment by Zerowhizkey** [comment]
> Kan också ha något att göra med mellanslag i mappnamnen, det är min andra gissning!

Jag chansar på det också! antar att det skulle kunna vara "Webbserver & databaser" jag har haft något liknande fel och ändrade min mapp till typ "Webbserver-databaser"

**Comment by ChrysostomouNygren** [comment]
Dess felmeddelande får inte med webbserver &, utan kollar bara från databaser. Så det är nog 99% risk att mellanslagen ställer till det.

**Comment by linda-94-andersson** [comment]
> Har hittat ett par andra med samma problem och som också har det liggandes på OneDrive. Kan du testa om du får samma problem med projektet utanför en OneDrive-mapp?

Jag testade att ta bort mellanslagen på mappen med det hjälpte ej. 
Gjorde ett tomt projekt utanför OneDriven och då kunde jag installera sqlite3 med npm. Men riktigt skumt! Skolan har som policy att vi ska använda OneDrive för backup av våra arbeten men den har varit en pain in the ass hela tiden! Får väl flytta projektet och inte glömma pusha till GIT så att data inte försvinner om något skulle hända med min laptop.

**Comment by linda-94-andersson** [comment]
Tack för svar folks! Jag stänger denna issue nu då jag har installerat sqlite3 i mitt projekt.
