### ISSUE TITLE
Varför får jag bara uppdaterat svar på andra uppdateringen?

### ISSUE THREAD

**Issue by alvablot** [cme-osuka/webbserverdatabaser#28]
Jag har skapat en databas med tillhörande tabeller och korrekt data. Jag kan hämta, lägga till, uppdatera och deleta utan problem. Det som stör är att responsen som skickas inte kommer som svar direkt, utan jag måste skicka requesten två gånger eller uppdatera servern innan JSON objekten visas med den uppdaterade listan. Bli samma i insomnia eller om jag skickar direkt från consolen. Någon som har någon idé.

```

**Comment by Zerowhizkey** [comment]
Kan du behöva nån await till något?

**Comment by alvablot** [comment]
Kanske det. Men var?

**Comment by Zerowhizkey** [comment]
Ingen aning :D jag skulle ta ett ställe och börja och fortsätta tills det funkar "OM det börjar funka"

**Comment by alvablot** [comment]
Jag var tvungen att göra mina funktioner asynk

**Comment by Zerowhizkey** [comment]
Då var jag inte ute och cykla iaf! :D
