### ISSUE TITLE
socket.username hjälp

### ISSUE THREAD

**Issue by M00NB3VM** [cme-osuka/webbserverdatabaser#35]
Jag sätter min socket.username = username (tar emot som input).
När jag joinar ett rum så skriver jag ut att just denna användare har joinat. Detta fungerar.

MEN
När jag lämnar rummet får jag att "undefined har lämnat rummet".
Det samma gäller när jag vill skriva ut vem som skickat meddelandet. 

Som jag förstår det räcker det med att sätta socket.username för att sedan ha tillgång till det valda användarnamnet/ kunna använda socket.username igen?

Server:
socket.on("set_username", (name) => {
    socket.username = name;
  });

Efter detta, hur kommer jag åt socket.username?

**Comment by sawariz0r** [comment]
Försöker du läsa ut socket.username i frontenden eller backenden när du får undefined?

**Comment by M00NB3VM** [comment]
Både och, då jag får absolut ingenting att fungera ~

**Comment by sawariz0r** [comment]
Vad jag vet ska man inte kunna komma åt datan som man sparar under `socket.<whatever>` i frontenden, så den kommer vara null. Och om den är undefined funderar jag på om det är något med raden `socket.username = name` som är tokigt..

Kan det vara så att `name` som du tar emot är undefined?

**Comment by M00NB3VM** [comment]
Dag tre har jag nu förstått att problemet uppstod då jag skickade användaren till en ny sida vid klick av join room. Och att användaren då re-connectade med ett nytt socket-id. Känner att jag inte fullt har förstått hur jag ska lägga upp detta projekt. Men issuen kan stängas.
