### ISSUE TITLE
Multipla loggningar vid fs.writeFile

### ISSUE THREAD

**Issue by Binnaz-CME** [cme-osuka/webbserverdatabaser#37]
Hej!
Jag får multipla loggningar/skrivningar i min json-fil när jag försöker logga mina meddelanden med fs.writeFile. Jag har provat med både async och vanliga metoden men det gör ingen skillnad. 

Vad gör jag för fel?

<img width="645" alt="Screenshot 2022-06-30 at 14 33 22" src="https://user-images.githubusercontent.com/92431375/176678660-2270365c-9c9c-417f-879a-f5b9df2f7d1d.png">

**Comment by M00NB3VM** [comment]
Testa att lägga socket.use utanför din socket.on. Förslagsvis direkt efter/inom din io.on.

**Comment by Binnaz-CME** [comment]
Tack! Jag tror att det hjälpte :-)
