### ISSUE TITLE
Byta version i Node med nvm.

### ISSUE THREAD

**Issue by aleksmagnusson** [cme-osuka/webbserverdatabaser#4]
Behöver hjälp med att byta version i node med nvm. :)
V. 17.3.1, Windows.

**Comment by vinsjo** [comment]
Om du kör följande kommandon kan du installera och byta till LTS-versionen:
nvm install lts
nvm use lts

**Comment by aleksmagnusson** [comment]
Löste issue/problem med kodrad:
I terminalen:
$ . ~/.nvm/nvm.sh
sedan
$ nvm install 16
>> Du använder nu node v.16.15.0 (npm v8.5.5)

Testa att rätt version stämmer med: $ node -v
för att se att det är rätt version installerad.

(Dubbelkolla med "$ nvm use 16" ).

**Comment by sawariz0r** [comment]
https://dev.to/duhbhavesh/nvm-command-not-found-1ho
