### ISSUE TITLE
Kan posta från Insomnia, men ej från frontend

### ISSUE THREAD

**Issue by kevlio** [cme-osuka/webbserverdatabaser#9]
Hej!
Lyckas posta todos från Insomnia, men inte från Frontenden.

Backendkod:
`  if (req.url === "/todos") {
    if (req.method === "POST") {
      console.log("POST");
      req.on("data", (chunk) => {
        const newTodo = JSON.parse(chunk);
        todos.todos.push(newTodo);
        const stringifiedTodos = JSON.stringify(todos, null, "\t");
        res.statusCode = 200;
        res.end();
        fs.writeFile("todos.json", stringifiedTodos, (err) => {
          if (err) throw err;
          console.log("Added todo");
        });
      });
    }
  }`

Axios request (som funkar i Insomnia, men ej från frontend):
`const options = {
  method: "POST",
  url: "http://localhost:5000/todos",
  headers: { "Content-Type": "application/json" },
  data: {
    id: "INSOMNIA",
    todo: "ISSUE",
    date: "2022-05-16",
    time: "14:58",
    prio: "high",
    completed: "false",
  },
};
axios
  .request(options)
  .then(function (response) {
    console.log(response.data);
  })
  .catch(function (error) {
    console.error(error);
  });`

Pending:
![image](https://user-images.githubusercontent.com/92679720/168599727-fc92b702-1961-45f8-8afc-60b5cbe540a1.png)
Headers:
![image](https://user-images.githubusercontent.com/92679720/168599802-d927b327-3a83-43cc-92c8-a3d369fd7903.png)
Payload:
![image](https://user-images.githubusercontent.com/92679720/168599849-da5b58cd-0759-4e81-9ed0-991eaf3baea6.png)
Initiator:
![image](https://user-images.githubusercontent.com/92679720/168599922-0fc4cc4a-fb85-4853-ae4f-10420b10999c.png)
Timing:
![image](https://user-images.githubusercontent.com/92679720/168600111-ba05b7fb-1586-4784-9ab5-fa3f037f03ab.png)
Timing "Stalled":
![image](https://user-images.githubusercontent.com/92679720/168600158-91561544-e221-45e6-b2db-7b0ed9d9b365.png)

Vänliga hälsningar
Kevin

**Comment by antonjaldegren** [comment]
Jag är inte bekant med att skriva axios.request(), det kanske är ett annat som också funkar. Men har du provat att skriva såhär istället? :)

```
axios
	.post("http://localhost:5000/todos", {
		id: "INSOMNIA",
		todo: "ISSUE",
		date: "2022-05-16",
		time: "14:58",
		prio: "high",
		completed: "false",
	})
	.then(function (response) {
		console.log(response.data);
	})
	.catch(function (error) {
		console.error(error);
	});
```

**Comment by kevlio** [comment]
> Jag är inte bekant med att skriva axios.request(), det kanske är ett annat sätt som också funkar. Men har du provat att skriva såhär istället? :)
> 
> ```
> axios
> 	.post("http://localhost:5000/todos", {
> 		id: "INSOMNIA",
> 		todo: "ISSUE",
> 		date: "2022-05-16",
> 		time: "14:58",
> 		prio: "high",
> 		completed: "false",
> 	})
> 	.then(function (response) {
> 		console.log(response.data);
> 	})
> 	.catch(function (error) {
> 		console.error(error);
> 	});
> ```

@antonjaldegren tack för svar Anton! Verkar dock inte vara där som problemet ligger. 
Testat 100 olika sätt att skriva axios posten på och även testat vanlig fetch... 
Nästan så jag tror att det är min dator/webbläsare som är problemet. Ska få upp det på Github om någon vill testa koden :)

**Comment by antonjaldegren** [comment]
Hmm, spännande!🤨

**Comment by kevlio** [comment]
Här är Github repot: https://github.com/kevlio/todo-backend
Om nån skulle vilja testa på sin egen dator skulle det vara hjälpsamt :)

**Comment by kevlio** [comment]
wow @antonjaldegren du är en hjälte <3 Tack så mycket! Gjorde min dag.
Jag hade testat vanlig axios post och res.setHeader på serversidan. Men tydligen inte samtidigt då :d Ska sluta skylla på min stackars jobbdator.

@cme-osuka poäng och guldstjärna till @antonjaldegren. Denna issue är löst.

**Comment by antonjaldegren** [comment]
Ingen orsak, bara kul att få se något annat än min egna kod hela tiden!☺️✨

Btw så behövde det inte ändras till axios.post på klienten, axios.request-lösningen du hade skrivit funkade lika bra👍

**Comment by sawariz0r** [comment]
Värt att läsa: [What is a Preflight request?](https://livebook.manning.com/book/cors-in-action/chapter-4/ch04lev1sec1)

Det är den del av CORS, där webbläsaren gör en s.k. Preflight-request för att kolla vilka metoder, headers, origins vi tillåter på vår backend INNAN den gör vår faktiska request. Skulle ni försöka göra en request med ex. DELETE-verbet och console.logga den inkommande requestens metod med `req.method` så kommer ni se att den inte skriver ut DELETE som metod - utan OPTIONS.

Där vi behöver skicka tillbaka ett svar till denna requesten, ex. som Nils delade;

```js
res.setHeader("Access-Control-Allow-Origin", "*");
res.setHeader("Content-Type", "application/json");
res.setHeader("Access-Control-Allow-Credentials", "true");
res.setHeader("Access-Control-Allow-Methods", "GET, PATCH, DELETE, OPTIONS, POST, PUT");

if (req.method === "OPTIONS") {
  res.statusCode = 200;
  res.end();
  // Eventuellt en return; här för att förhindra att den går vidare till de faktiska endpointsen nedan.
  return;
}

...början på dina endpoints
```
